// Generated by scripts/build-sounds.py — do not edit by hand.
// Clip positions in public/sounds/sprite.mp3: [start seconds, duration seconds].
export const SPRITE_URL = "/sounds/sprite.mp3?v=4e1022edb1";

export const SPRITE_CLIPS = {
  "bark1": [
    0.05,
    0.3943
  ],
  "bark2": [
    0.5643,
    0.3544
  ],
  "bark3": [
    1.0388,
    0.3245
  ],
  "bark4": [
    1.4832,
    0.5041
  ],
  "bark5": [
    2.1073,
    0.7136
  ],
  "yip1": [
    2.9409,
    0.2247
  ],
  "yip2": [
    3.2856,
    0.2247
  ],
  "yip3": [
    3.6304,
    0.2247
  ],
  "yip4": [
    3.9751,
    0.2247
  ],
  "yip5": [
    4.3198,
    0.2397
  ],
  "woof1": [
    4.6795,
    0.2696
  ],
  "woof2": [
    5.0691,
    0.2846
  ],
  "whine1": [
    5.4737,
    0.4741
  ],
  "whine2": [
    6.0678,
    0.2646
  ],
  "whine3": [
    6.4524,
    0.2546
  ],
  "howl": [
    6.8271,
    1.6016
  ],
  "pant": [
    8.5487,
    3.18
  ],
  "clack1": [
    11.8487,
    0.1734
  ],
  "clack2": [
    12.1421,
    0.2927
  ],
  "clack3": [
    12.5547,
    0.1771
  ],
  "clack4": [
    12.8518,
    0.2927
  ],
  "clack5": [
    13.2645,
    0.2927
  ],
  "plank1": [
    13.6772,
    0.468
  ],
  "plank2": [
    14.2652,
    0.4421
  ],
  "paw1": [
    14.8273,
    0.1952
  ],
  "paw2": [
    15.1425,
    0.1719
  ],
  "paw3": [
    15.4344,
    0.1289
  ],
  "thud": [
    15.6832,
    0.2102
  ],
  "thudHeavy": [
    16.0135,
    0.5994
  ],
  "sleighbells": [
    16.7329,
    4.68
  ],
  "cork": [
    21.5329,
    0.45
  ],
  "horn1": [
    22.1029,
    0.6837
  ],
  "horn2": [
    22.9066,
    1.1576
  ],
  "bird1": [
    24.1842,
    2.68
  ],
  "bird2": [
    26.9842,
    1.37
  ],
  "thunder": [
    28.4742,
    3.48
  ],
  "leaves": [
    32.0742,
    1.93
  ]
};
