import Head from "next/head";
import Image from "next/image";
import Layout from "../components/layout";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Blackdog Raffle</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <div class="container mx-auto text-white">
          <nav class="flex items-center py-4 lg:px-48 p-5 bg-slate-800">
            <Image
              src="/assets/black_dog_logo.png"
              alt="Blackdog Logo"
              width={50}
              height={100}
            />
            <h1 class="text-xl font-bold ml-3 uppercase tracking-[.1rem]">
              Blackdog Raffle
            </h1>
          </nav>
          <div class="mx-5 py-16 lg:mx-48"></div>
        </div>
      </Layout>
    </div>
  );
}
